# Workflow for building and deploying LDoc to Artifact, and optionally Pages
name: Deploy LDoc to Artifact (Optional Pages)

on:
  # Runs on pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy_page:
        description: 'Deploy to GitHub Pages?'
        required: false
        default: false
        type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and PR interactions
permissions:
  contents: read

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Isolate LDoc source
        run: |
            mkdir "${{ runner.temp }}/source/"
            for f in ./* ; do
                if [ -f "$f" ]; then
                    cp "$f" "${{ runner.temp }}/source/$f"
                fi
            done
      - name: Setup Pages
        if: ${{ inputs.deploy_page }} 
        uses: actions/configure-pages@v5
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: 5.1
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0
      - name: Install Dependencies
        run: |
            luarocks install luafilesystem
            luarocks install penlight
            luarocks install ldoc
      - name: Run LDoc
        run: ldoc "${{ runner.temp }}/source/" --template "${{ runner.temp }}/source/" --format="markdown" -d "${{ runner.temp }}/LDOC"
      - name: Upload Artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
            name: 'LDOC_zip'
            path: "${{ runner.temp }}/LDOC"
            retention-days: 0
      - name: Create Artifact (TAR)
        if: ${{ inputs.deploy_page }} 
        run: |
            chmod -c -R +rX "${{ runner.temp }}/LDOC/" | while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
            done
            tar \
              --dereference --hard-dereference \
              --directory "${{ runner.temp }}/LDOC/" \
              -cvf "${{ runner.temp }}/LDOC_tar.tar" \
              --exclude=.git \
              --exclude=.github \
              --force-local \
              "."
      - name: Upload Artifact (TAR)
        uses: actions/upload-artifact@v4
        with:
          name: 'LDOC_tar'
          path: "${{ runner.temp }}/LDOC_tar.tar"
          retention-days: 0

  # Optional page deployment job
  deploy:
    if: ${{ inputs.deploy_page }} 
    
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5 # or specific "vX.X.X" version tag for this action
        with:
          artifact_name: 'LDOC_tar'
